import { describe, expect, it } from "vitest";
import { parseLuaAssignments, parseLuaData } from "./lua.ts";

describe("parseLuaData", () => {
  it("parses PoB-style keyed tables", () => {
    const lua = `
      -- This file is automatically generated, do not edit!
      return {
        ["Metadata/Items/Currency/Essence1"] = {
          name = "Lesser Essence of the Body", type = "Life", tierLevel = 12,
          mods = { ["Helmet"] = "IncreasedLife3", ["Ring"] = "IncreasedLife2", },
        },
      }
    `;
    expect(parseLuaData(lua)).toEqual({
      "Metadata/Items/Currency/Essence1": {
        name: "Lesser Essence of the Body",
        type: "Life",
        tierLevel: 12,
        mods: { Helmet: "IncreasedLife3", Ring: "IncreasedLife2" },
      },
    });
  });

  it("parses array tables, negatives, booleans, and nil", () => {
    const lua = `return { list = { 1, -2.5, "three" }, flag = true, off = false, gone = nil }`;
    expect(parseLuaData(lua)).toEqual({
      list: [1, -2.5, "three"],
      flag: true,
      off: false,
      gone: null,
    });
  });

  it("handles escaped strings", () => {
    const lua = String.raw`return { text = "a \"quoted\" word\nnext line" }`;
    expect(parseLuaData(lua)).toEqual({ text: 'a "quoted" word\nnext line' });
  });

  it("represents mixed tables with a reserved array key", () => {
    const lua = `return { "a", "b", key = "value" }`;
    expect(parseLuaData(lua)).toEqual({ key: "value", __items: ["a", "b"] });
  });

  it("rejects files that are not a single return", () => {
    expect(() => parseLuaData("local x = 1")).toThrow(/return/);
  });
});

describe("parseLuaAssignments", () => {
  it("parses PoB Bases-style assignment files", () => {
    const lua = `
      -- This file is automatically generated, do not edit!
      local itemBases = ...

      itemBases["Wooden Club"] = {
        type = "One Hand Mace",
        tags = { default = true, mace = true, },
        weapon = { PhysicalMin = 6, PhysicalMax = 10, AttackRateBase = 1.45, },
        req = { },
      }
      itemBases["Fur Plate"] = {
        type = "Body Armour",
        armour = { Armour = 66, MovementPenalty = 0.05, },
        req = { str = 10, },
      }
    `;
    expect(parseLuaAssignments(lua)).toEqual({
      "Wooden Club": {
        type: "One Hand Mace",
        tags: { default: true, mace: true },
        weapon: { PhysicalMin: 6, PhysicalMax: 10, AttackRateBase: 1.45 },
        req: [],
      },
      "Fur Plate": {
        type: "Body Armour",
        armour: { Armour: 66, MovementPenalty: 0.05 },
        req: { str: 10 },
      },
    });
  });
});
